source_list:
#  - CP
#  - SB
  - OL
#  - ADDR

s3_conf:
  s3_bucket: ketandatabucket
  staging_dir_loc: staging

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query: "(select * from testdb.TRANSACTIONSYNC) as t"

OL:
  sftp_conf:
    filetype: csv
    delimiter: |
    directory: /home/ubuntu/data

ADDR:
  mongodb_config:
    database: school
    collection: students

CP:
  redshift_conf:
    host: your_redshift_host
    port: your_redshift_port
    database: your_database_name
    filetype: csv
    delimiter: |
